# Generated by Django 5.1.7 on 2025-03-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_alter_team_league_alter_userteam_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('FW', 'Forward'), ('MF', 'Midfielder'), ('DF', 'Defender'), ('GK', 'Goalkeeper')], max_length=2),
        ),
    ]
