# Generated by Django 5.1.7 on 2025-03-14 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_alter_team_league_alter_userteam_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='defense',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='passing',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='shooting',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='speed',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='stamina',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='league.league'),
        ),
        migrations.DeleteModel(
            name='UserTeam',
        ),
    ]
